### ISSUE TITLE
Feature Request: Passing a file or screenshot into the chat

### ISSUE THREAD

**Issue by Braunson** [mydnic/laravel-kustomer#1]
It would be handy to have a guest or user pass a file or screenshot into the conversation. This could be an config option as well.

I would suggest for screenshots, using the HTML2Canvas package (https://html2canvas.hertzen.com) which is super handy!

**Comment by mydnic** [comment]
I'll look into that !

**Comment by mydnic** [comment]
To clarify what I'm going to implement, it will be an option in the configuration file. If set to true, when the user sends his feedback, a screenshot will be taken and sends to the server automatically. Thus no file input in the form :)

**Comment by mydnic** [comment]
Fixed in latest build 💪
