### ISSUE TITLE
Feature Request: Translation for text

### ISSUE THREAD

**Issue by stephanrueschenbaum** [mydnic/laravel-kustomer#3]
It would be great, if we can define a localization string in the config file instead of passing the localized text directly. E.g. "feedback.successMessage" instead of "Thank you for your feedback!" and pass that string to the Translation helper function.

**Comment by stephanrueschenbaum** [comment]
And please provide translation option for all texts, like "Give feedback", "Type your Feedback here..." or "Send feedback".

**Comment by n0n0n0n0** [comment]
totally agreed

**Comment by mydnic** [comment]
I've begin some work about this feature. I've isolated the component texts in translation files. I'll think about how to translate the feedback questions

**Comment by mydnic** [comment]
Feature added in v1.0
This is a breaking change so you will have to reinstall the package
