### ISSUE TITLE
Metadata on the feedback

### ISSUE THREAD

**Issue by kodameraadam** [mydnic/laravel-kustomer#48]
Great package! I have some feature requests to make the package even better.

**Add date and time**
It would be wonderful to add a timestamp to the post so it's easier to place in a context.

Screenshot for visual example:

![Screenshot 2019-12-17 kl  13 27 35](https://user-images.githubusercontent.com/36274715/70995600-38b71e00-20d1-11ea-8cba-b06078adf509.png)

**User**
For us, and for the client, it would be good to collect which user is submitting the feedback.

Once again - great package. Good job!

**Comment by mydnic** [comment]
Hello :)

Thanks for the kind words!

Actually the data are already stored, so I just needed to update the [nova-kustomer](https://github.com/mydnic/nova-kustomer) pacakge.

You can update the nova-kustomer package to v1.3 and the new information should appear in Nova 👍

**Comment by kodameraadam** [comment]
Wonderful! Will update right away!
