### ISSUE TITLE
Feature Request: Screen elements capturing with feedback

### ISSUE THREAD

**Issue by mshoaibdev** [mydnic/laravel-kustomer#55]
It is a feature if you want to implement it. I think adding a screen capturing with feedback would be greate like saberfeedback.com provides in their feedback form.

**Comment by mydnic** [comment]
It is already supported by the package :)

Check the config file
https://github.com/mydnic/laravel-kustomer/blob/master/config/kustomer.php#L103

**Comment by mydnic** [comment]
It's not as powerful as saberfeedback though

**Comment by mshoaibdev** [comment]
Okay, thank you.
